### ISSUE TITLE
Tasks that are built with `--has-batch` and `--no-lambda` still have a lambda block in definition.yml

### ISSUE THREAD

**Issue by stark525** [cirrus-geo/cirrus-geo#123]
When creating a batch only task:
```
cirrus task create a_task --has-batch --no-lambda
```

In `definition.yml`, there is still a lambda block, even though `--no-lambda` is specified. The desired behavior would this would not get added to the `definition.yml`, since it should not be used.

**Comment by jkeifer** [comment]
It looks like this may have been fixed already, but while testing I reconsidered the UI here in light of the loss of my initial bias in preference of lambda task.

Now, instead of defaulting lambda on, I made the task type a required option via `-t` or `--type`. Valid values are `batch` and `lambda`, and it can be specified multiple times in the case of a task that is both `batch` and `lambda`. For example:

````
❯ cirrus create task -t batch batch-task 1234
task batch-task created
❯ cirrus create task -t lambda lambda-task 1234
task lambda-task created
❯ cirrus create task -t lambda --type batch batch-lambda-task 1234
task batch-lambda-task created
```

In any case, running the three tests above showed the expected behavior, i.e., the lambda block was omitted from the `definition.yml` in the case of batch-only.
