### ISSUE TITLE
Give builtin ComputeEnvironments a name

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#129]
ComputeEnvironments can be provided a ComputeEnvironmentName in the properties.  The basic compute environments deployed have names like `cirrus-dev-basic-spot`, while the buildin tasks that can be batch via the lambda runner have names like `AddPreviewComputeEnviron-TZmYvboWLdVZhlVy`, `ConvertToCOGComputeEnvir-fC1IWrUBj9WRLVQ5`

**Comment by jkeifer** [comment]
The problem here is if we name the compute environments and ever want to change the settings, the update will fail. Compute environments are replace-only, but having a specific name breaks the replace operation due to CF trying to create the new instance before deleting the old one.

Frankly, I think this reveals a problem with cirrus trying to manage _any_ of these batch resources as built-ins. Properly coordinating batch resource updates can be extremely complicated and difficult, depending on uptime requirements, and it seems antithetical to try to hide that from end users in the name of making it "easier".

I think we need a new idea here. I'm not sure what it is yet, other than we have already discussed moving these tasks out into a plugin package. Perhaps that's not so much a plugin that provides the full task definitions as it is a code library and a command to initialize a project version of these tasks, so the user has more explicit control over their configuration.

**Comment by jkeifer** [comment]
OBE as built in compute environments have been removed from v1.
