### ISSUE TITLE
Upgrade serverless to v3

### ISSUE THREAD

**Issue by marchuffnagle** [cirrus-geo/cirrus-geo#152]
Cirrus is currently using serverless v1 for deployments: https://github.com/cirrus-geo/cirrus-geo/blob/main/src/cirrus/core/constants.py#L5

Serverless v1 and v2 default to using Node 12, which means that the custom resource lambdas that they deploy use Node 12 as well. This was [fixed in Serverless](https://github.com/serverless/serverless/pull/10379), and is part of the [3.0.0 release](https://github.com/serverless/serverless/blob/HEAD/CHANGELOG.md#300-2022-01-27).

Node 12 reached end-of-life on April 30, 2022. AWS has stated:

> Starting November 14, 2022, Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions, and functions using Node.js 12 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 12 runtime. Starting December 14, 2022, you will no longer be able to update existing functions using the Node.js 12 runtime.

Cirrus needs to be updated to use serverless v3, or there's a risk that deployments will stop working in the next few months.

**Comment by jkeifer** [comment]
This issue is effectively encapsulated in #139, as we need to support newer versions of serverless to support containerized lambdas, but calling it out explicitly as a separate issue is not a bad thing.

The work to support that issue and inherently serverless >=3.0.0 is already in the PR #150. As such I will add this issue to milestone 0.7.0 and ensure it is closed out when that PR is merged.
