### ISSUE TITLE
Processing costs 

### ISSUE THREAD

**Issue by tvance34** [cirrus-geo/cirrus-geo#25]
As a user with multiple cirrus workflows, I want to be able to track processing costs associated with each individual workflow.

**Comment by stark525** [comment]
This poses some challenges with spot instances, but I'm envisioning a simple boto script that will query the spot market based on the resource definition that's defined, with a disclaimer that this value may change.

We may want to consider adding `SpotMaxTotalPrice`, if possible, so that we can predict "Here's the maximum this workload should charge you"

Do we want to actually run the workflow once and predict, or have users estimate how long their compute in the workflow will take?

**Comment by tvance34** [comment]
@stark525 curious how well we could predict the costs, and what costs (if any) would be incurred for doing that prediction.  curious how often the estimate would line up pretty closely with the actual cost as well and how much confidence a user could have in it.  definitely think it could be valuable though and would be an awesome feature to go along with just seeing a breakout of costs for each job/workflow.

**Comment by jkeifer** [comment]
Cost estimation is still a pain point. It would be great if we had the ability to inspect costs via the FilmDrop UI but at this time work related to costing is not planned.

We will revisit this in the future when we have a better story around the costs and how to track them in a meaningful and useful way.
