### ISSUE TITLE
Make data bucket user configurable

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#47]
The main Cirrus data bucket is where all the STAC Items and the data themselves will get uploaded to (unless a workflow specifies another location).

Right now it is named automatically with the normal serverless method - `cirrus-<stage>-<randomchars>`

Since users will often interface directly with the bucket, it seems reasonable that you'd want to have something more readable and specify the bucket name exactly.

- change default bucket name to `cirrus-<stage>-data`
- Update install/deploy docs to clearly indicate how to change the name
- Users may want to use an already existing bucket, also allow for specifying existing bucket and not creating a new one

**Comment by trevorskaggs** [comment]
This is currently already possible by overriding in your projects cirrus.yml.  Need additional documentation to explain this process.

**Comment by jkeifer** [comment]
I've looked into this issue a bit more and I have some findings.

1. If one overrides the `Data` bucket in a project with a different name it'll work as long as a bucket with that name does not already exist.
2. Changing the name of the `Data` bucket after the stack is initially created will result in a cloudformation error _if the `Data` bucket is not empty_. If it is empty, a new bucket will be created and the old bucket will be deleted. But if it is not empty, the new bucket will be created and the old bucket will not be able to be removed. However, I believe the new bucket will not be removed in the cloudformation rollback, so one can always copy the data to the new bucket and manually remove the old bucket. More testing would be required to confirm these details.
3. If overriding the `Data` bucket to specify a bucket that _already exists_, cloudformation will fail with an error because it cannot simply "adopt" existing resources. There appears to be a way to import existing resources (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-existing-stack.html), but I am struggling to see how it could work in this case. I believe we'd need a way to remove `Data` from the stack so that a new `Data` could be defined in the stack for that new resource. It would also appear to be a rather manual process of modifying an already-applied cloudformation template and ensuring those same changes are persisted in the cirrus project.

All this said, which bucket cirrus actually uses for data is controlled by an env var (typically set at the global level in cirrus.yml):

```
CIRRUS_DATA_BUCKET: !Ref Data
```

Setting this var to reference something other than `Data` will allow the user to use a different bucket without any weird cloudformation overrides/imports/etc. As long as users can accept having the `Data` bucket automatically created and existing in their account, then they can use whatever bucket they want as easily as changing this env var.

If we need to accommodate disabling the `Data` bucket, or allowing that key to be used for an imported resource, then we have a fair bit more work to do here. But if we can assume the existence of the `Data` bucket is not a problem in all cases then we don't really have an action item here beyond a short bit of documentation.

@matthewhanson thoughts? I'm of the opinion we simply close this issue out until we have a specific reason to pursue such changes, but if you think we need to explore more work around disabling `Data` then I can create a ticket for that in the backlog.
