### ISSUE TITLE
cirrus-lib dependency

### ISSUE THREAD

**Issue by matthewhanson** [cirrus-geo/cirrus-geo#55]
The `requirements.txt` includes cirrus-lib, however it's not clear if cirrus-lib is really used by the Cirrus CLI, or if it is a dependency of tasks that are packages by the Cirrus CLI.

When packaging tasks does it include this requirements.txt file?  Is there a way to specify global requirements for all tasks?

**Comment by jkeifer** [comment]
Cirrus-lib is a packaging dependency, and is currently not used by the cirrus CLI.

When setting up the lambda directories for packaging, a `requirements.txt` file created for each lambda. The contents of that file include any python dependencies listed under the `python_requirements` key in the lambda's `definition.yml` file, along with cirrus-lib. The version specified for cirrus-lib is extracted from the cirrus package metadata, such that the version in the cirrus `requirements.txt` will also be used for lambda packaging as a "global requirement".

Beyond that, we do not currently support global requirements for all lambdas (I say lambda rather than task here as all lambda-type components are packaged the same way at the moment).

**Comment by trevorskaggs** [comment]
Potentially OBE by inclusion of cirrus-lib

**Comment by jkeifer** [comment]
See #66 for cirrus-lib inclusion.

**Comment by jkeifer** [comment]
#89 changes how the cirrus-lib dependency is handled. Now, we install cirrus-lib in all lambdas as part of the `cirrus build` process by copying the `cirrus.lib` python package into the cirrus build dir, and symlinking that into each of the lambda directories within. When serverless packages the lambdas, it bundles cirrus-lib in as well.

Some changes to allow this to work mean that the lambda `requirements.txt` files for the serverless python plugin no longer gets the cirrus-lib dependency version injected, rather all dependencies of cirrus-lib (based on package inspection using `importlib.metadata`) are injected, and cirrus-lib itself is omitted as it does not need to be pip-installed.

Part of making this all work, and looking further at the serverless python plugin made me realize that we already had a top-level `pythonRequirements` config in `cirrus.yml`, which per the plugin supports an `include` key, to provide a list of global dependencies for all lambda. I added support in the dependency injection (should I call it that despite its other connotations?) for such globally-defined requirements, even though using that feature appears to be an anti-pattern.

Anyway, cirrus-lib is still not used directly by cirrus-geo other than as the copy source for the lambdas. In that sense it is actually required to be installed to the python env now, whereas before it was not really required.

@matthewhanson I am going to close this issue, but if you have further concerns please reopen.
